#' Summarize models
#'
#' This function generates a table with summary stats of each model
#' @param models A list of model objects generated by make_xgb_models
#' @keywords scores
#' @import glue
#' @export
#' @examples
#' get_scores_table(my_models)
get_scores_table <- function(models){
  
  n_term_table <- map(models,"important_features") %>%
    map(length) %>%
    as_tibble() %>%
    pivot_longer(everything(),names_to="brd",values_to="n_terms")
  
  error_table <- map(models[n_term_table %>% filter(n_terms > 0) %>% pull(brd)],"predictions_error") %>% 
    map(mean, na.rm = T) %>% 
    as_tibble() %>%
    pivot_longer(everything(),names_to="brd",values_to="error")
  
  r_table <- map(models,"scores") %>%
    map(mean) %>% 
    as_tibble() %>%
    pivot_longer(everything(),names_to="brd",values_to="r")
  
  r_squared_table <- map(models, "scores") %>%
    map(function(x) x^2) %>%
    map(mean) %>% 
    as_tibble() %>%
    pivot_longer(everything(),names_to="brd",values_to="r.squared")
  
  scores_table <- r_table %>%
    left_join(r_squared_table, by = "brd") %>%
    left_join(error_table, by = "brd") %>% 
    left_join(n_term_table, by = "brd") %>%
    arrange(desc(r))  
  
  
  return(scores_table)
  
}