#' Plot top contributions (internal function)
#'
#' This function generates a plot of the top contributing features for the top n models.
#' @keywords plot
#' @import ggplot2 cowplot purrr
#' @examples
#' plot_top_contributors(shap_table, name, 10)
helper_plot_top_contributors <- function(shap_table, name, n, color = "#52565e"){
  
  shap_table <- shap_table %>% top_n(n, wt=value)
  shap_table$term <- factor(str_to_upper(shap_table$term), levels = rev(str_to_upper(shap_table$term)))
  shap_table$labels <- abbreviate(as.character(shap_table$term), minlength = 10, dot = T)
  p <- ggplot(shap_table, aes(x=term,y=value))+geom_bar(stat="identity", fill = color)+coord_flip()+
    labs(x="Feature",y="Contribution",subtitle=str_to_upper(word(name,2,sep="_")))+
    scale_x_discrete(labels = shap_table$labels)
  
  return(p)
  
}

#' Plot top contributions
#'
#' This function generates a plot of the top contributing features for the top n models.
#' @param models A list of model objects generated by make_xgb_models
#' @param models_to_use A vector of model names to restrict the plot to.
#' @param data_to_use If "training" (default), it will use the full training data. If anything else, it will use the new predictions (must have used add_predictions before).
#' @param n_predictors The maximum number of predictors to show per plot.
#' @param n_columns If multiple models are being plotted, how many columns in the plot grid to use.
#' @param color The color of the bars in the plot.
#' @keywords plot
#' @import ggplot2 cowplot purrr
#' @export
#' @examples
#' plot_top_contributors(shap_table, name, 10)
plot_top_contributors <- function(models, models_to_use = NULL, data_to_use = "training", n_predictors = 10, n_columns = 5, color = "#52565e"){
  
  # Restrict the plot to the top 10 most variable predictions across our clusters
  models_of_interest <- models
  if(!is.null(models_to_use) && length(models_to_use) > 0){
    models_of_interest <- models[models_to_use]
  }
  
  if (data_to_use == "training"){
    shap_tables <- map(models_of_interest, "feature_contribution")
  } else {
    shap_tables <- map(models_of_interest, "new_data") %>% map("feature_contribution")
  }

  p <- plot_grid(plotlist = imap(shap_tables, helper_plot_top_contributors, n = n_predictors, color = color), align='v', ncol=n_columns)

  return(p)
  
}


#' Overlay predictions on a dimensional reduction plot
#'
#' This function generates a dimensional reduction plot with predictions overlayed on each cell.
#' @param scRNA_data A Seurat object with predictions appended (e.g. using append_predictions_to_seurat)
#' @param perturbation The name of the perturbation whose predictions we want to plot.
#' @param reduction The dimensionality reduction technique to show (default = 'umap')
#' @param dims A 2-element vector with the dimensions to plot (default = c(1,2))
#' @param fixed_color_scale Default = FALSE. If TRUE, the color scale will be fixed from 0 to 1.
#' @keywords plot dimplot
#' @import Seurat ggplot2 cowplot
#' @export
#' @examples
#' plot_top_contributors(shap_table, name, 10)
plot_predictions_dimplot <- function(scRNA_data, perturbation, 
                                     reduction = "umap",
                                     dims = c(1,2),
                                     fixed_color_scale = FALSE){
  
  feature_data <- scRNA_data@meta.data[,perturbation]
  embed_data <- scRNA_data[[reduction]]@cell.embeddings
  dim_1 <- embed_data[,dims[1]]
  dim_2 <- embed_data[,dims[2]]
  
  plot_data <- embed_data %>% cbind(feature_data)
  
  
  p <- ggplot()+
    geom_point(aes(x=dim_1,y=dim_2,color=feature_data))
  
  if(fixed_color_scale){
    p <- p + scale_color_distiller(palette = "RdYlBu", direction = -1, limits = c(0, 1))
  } else {
    p <- p + scale_color_distiller(palette = "RdYlBu", direction = -1)
  }
  
  
  p <- p + theme_bw(base_line_size = 0)+
    labs(color = perturbation, x = colnames(embed_data)[dims[1]], y = colnames(embed_data)[dims[2]])
  
  return(p)
  
}
