#' Summarize models
#'
#' This function generates a table with summary stats of each model
#' @param models A list of model objects generated by make_xgb_models
#' @keywords scores
#' @import glue
#' @export
#' @examples
#' summarize_models(my_models)
summarize_models <- function(models){
  
  n_term_table <- map(models,"important_features") %>%
    map(length) %>%
    as_tibble() %>%
    pivot_longer(everything(),names_to="brd",values_to="n_terms")
  
  error_table <- map(models[n_term_table %>% filter(n_terms > 0) %>% pull(brd)],"predictions_error") %>% 
    map(mean, na.rm = T) %>% 
    as_tibble() %>%
    pivot_longer(everything(),names_to="brd",values_to="error")
  
  r_table <- map(models,"scores") %>%
    map(mean) %>% 
    as_tibble() %>%
    pivot_longer(everything(),names_to="brd",values_to="r")
  
  r_squared_table <- map(models, "scores") %>%
    map(function(x) x^2) %>%
    map(mean) %>% 
    as_tibble() %>%
    pivot_longer(everything(),names_to="brd",values_to="r.squared")
  
  scores_table <- r_table %>%
    left_join(r_squared_table, by = "brd") %>%
    left_join(error_table, by = "brd") %>% 
    left_join(n_term_table, by = "brd") %>%
    arrange(desc(r))  
  
  
  return(scores_table)
  
}


#' Summarize predictions
#'
#' This function generates a table with predictions for each perturbation in a list of models.
#' @param models A list of model objects generated by make_xgb_models and with predictions added using add_predictions.
#' @keywords predictions
#' @import purrr
#' @export
#' @examples
#' summarize_predictions(my_models)
summarize_predictions <- function(models){
  
  predictions_table <- models %>% 
    map("new_data") %>%
    map("predictions") %>% 
    map(as_tibble, rownames = "sample") %>%
    reduce(left_join, by = "sample") %>%
    column_to_rownames("sample")
  
  colnames(predictions_table) <- names(models)
  
  return(predictions_table)
  
}


#' Summarize prediction error
#'
#' This function generates a table with prediction error for each perturbation in a list of models.
#' @param models A list of model objects generated by make_xgb_models and with predictions added using add_predictions.
#' @keywords predictions error
#' @import purrr
#' @export
#' @examples
#' summarize_predictions(my_models)
summarize_error <- function(models){
  
  error_table <- models %>% 
    map("new_data") %>% 
    map("predictions_error") %>% 
    map(as_tibble, rownames = "sample") %>%
    reduce(left_join, by = "sample") %>%
    column_to_rownames("sample")
  
  colnames(error_table) <- names(models)
  
  return(error_table)
  
}



